CREATE TABLE `competitions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`organizer` varchar(200),
	`category` varchar(100),
	`level` enum('国家级','省级','市级','校级'),
	`description` text,
	`requirements` text,
	`awards` text,
	`registrationStartDate` timestamp,
	`registrationEndDate` timestamp,
	`competitionDate` timestamp,
	`resultAnnouncementDate` timestamp,
	`officialWebsite` varchar(500),
	`contactInfo` text,
	`status` enum('即将开始','报名中','进行中','已结束') NOT NULL DEFAULT '即将开始',
	`isWhitelisted` boolean NOT NULL DEFAULT false,
	`viewCount` int NOT NULL DEFAULT 0,
	`isPublished` boolean NOT NULL DEFAULT true,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `competitions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `courses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`teacherName` varchar(100) NOT NULL,
	`teacherTitle` varchar(100),
	`teacherSchool` varchar(200),
	`teacherIntro` text,
	`subject` varchar(100) NOT NULL,
	`grade` varchar(50) NOT NULL,
	`description` text,
	`syllabus` text,
	`schedule` text,
	`location` varchar(200),
	`price` decimal(10,2) NOT NULL,
	`maxStudents` int,
	`currentStudents` int NOT NULL DEFAULT 0,
	`courseType` enum('一对一','小班课','大班课') NOT NULL,
	`duration` varchar(100),
	`startDate` timestamp,
	`endDate` timestamp,
	`contactPhone` varchar(20),
	`contactWechat` varchar(100),
	`isActive` boolean NOT NULL DEFAULT true,
	`viewCount` int NOT NULL DEFAULT 0,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `courses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `news` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`summary` text,
	`content` text NOT NULL,
	`category` varchar(50) NOT NULL,
	`coverImage` varchar(500),
	`author` varchar(100),
	`source` varchar(200),
	`publishDate` timestamp NOT NULL,
	`viewCount` int NOT NULL DEFAULT 0,
	`isPublished` boolean NOT NULL DEFAULT true,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `news_id` PRIMARY KEY(`id`)
);
